import { connectToDatabase } from '../config/db.js';

const doctorsData = [
  // --- DHAKA DISTRICT (12 Doctors) ---
  {
    name: "Prof. Dr. A. B. M. Abdullah",
    title: "Eminent Physician & Personal Physician to the Prime Minister (Former)",
    degree: "MBBS, MRCP (UK), FRCP (Edinburgh), FCPS (Medicine)",
    specialty: "Internal Medicine & Diabetes",
    experienceYears: 35,
    city: "Dhaka",
    hospital: "Central Hospital Limited",
    hospitalAddress: "House 02, Road 05, Green Road, Dhanmondi, Dhaka 1205",
    fee: 2000,
    rating: 4.98,
    reviewCount: 512,
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Mon", "Tue", "Wed"],
    timing: "5:00 PM - 9:00 PM",
    bio: "Ekushey Padak awardee and nationwide legendary internal medicine specialist. Expert in complex diagnostic medicine, diabetes, and infectious disease management.",
    contactPhone: "+880 1711-554433",
    email: "dr.abmabdullah@centralhospital.com",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: true
  },
  {
    name: "Prof. Dr. Pran Gopal Datta",
    title: "Senior Consultant ENT & Head Neck Surgeon",
    degree: "MBBS, MCPS, MSc (Audiology, UK), FCPS, PhD (Dhaka), FRCP (Glasgow)",
    specialty: "ENT (Ear, Nose, Throat)",
    experienceYears: 32,
    city: "Dhaka",
    hospital: "Green Life Hospital",
    hospitalAddress: "32, Bir Uttam KM Shafiullah Sarak, Green Road, Dhanmondi, Dhaka",
    fee: 2500,
    rating: 4.96,
    reviewCount: 489,
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sat", "Sun", "Tue", "Thu"],
    timing: "4:00 PM - 8:30 PM",
    bio: "Independence Day Award recipient and former Vice-Chancellor of BSMMU. Renowned international authority in otolaryngology, cochlear implants, and head-neck surgeries.",
    contactPhone: "+880 1711-998877",
    email: "pg.datta@greenlifebd.com",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: true
  },
  {
    name: "Prof. Dr. AQM Reza",
    title: "Senior Consultant & Head of Cardiology",
    degree: "MBBS, FCPS (Medicine), MD (Cardiology), FACC (USA)",
    specialty: "Cardiology",
    experienceYears: 24,
    city: "Dhaka",
    hospital: "Square Hospital",
    hospitalAddress: "18/F, Bir Uttam Qazi Nuruzzaman Sarak, Panthapath, Dhaka",
    fee: 1800,
    rating: 4.9,
    reviewCount: 328,
    photo: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Mon", "Tue", "Wed", "Sat"],
    timing: "5:00 PM - 9:00 PM",
    bio: "Internationally trained Interventional Cardiologist specializing in complex coronary angioplasty, pacemakers, and heart failure care.",
    contactPhone: "+880 1711-000111",
    email: "dr.reza@squarehospital.com",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: true
  },
  {
    name: "Prof. Dr. Sayeba Akhter",
    title: "Eminent Obstetrician, Gynecologist & Fistula Surgeon",
    degree: "MBBS, FCPS (OBGYN), MS (OBGYN), FICOG (India)",
    specialty: "Gynecology & Obstetrics",
    experienceYears: 30,
    city: "Dhaka",
    hospital: "MAMATA Maternal & Child Health Care",
    hospitalAddress: "House 12, Road 7, Dhanmondi, Dhaka",
    fee: 2000,
    rating: 4.94,
    reviewCount: 415,
    photo: "https://images.unsplash.com/photo-1594824813566-78a1ed6493f8?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Tue", "Thu"],
    timing: "4:00 PM - 8:00 PM",
    bio: "Ekushey Padak recipient and innovator of the Sayeba's Method for PPH management. Global pioneer in maternal healthcare and obstetric surgery.",
    contactPhone: "+880 1819-223344",
    email: "sayeba.akhter@mamata.org.bd",
    languages: ["Bangla", "English"],
    gender: "Female",
    isFeatured: true
  },
  {
    name: "Prof. Dr. Syed Atiqul Haq",
    title: "Senior Specialist Rheumatologist & Medicine Specialist",
    degree: "MBBS, FCPS (Medicine), MD (Rheumatology), FRCP (Glasgow)",
    specialty: "Rheumatology",
    experienceYears: 28,
    city: "Dhaka",
    hospital: "Bangabandhu Sheikh Mujib Medical University (BSMMU)",
    hospitalAddress: "Shahbag, Dhaka 1000",
    fee: 2000,
    rating: 4.95,
    reviewCount: 410,
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Mon", "Wed"],
    timing: "6:00 PM - 9:30 PM",
    bio: "Pioneer of Rheumatology in Bangladesh. Managing rheumatoid arthritis, lupus (SLE), gout, osteoarthritis, and autoimmune disorders.",
    contactPhone: "+880 1819-998877",
    email: "s.atiqul@bsmmu.edu.bd",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: true
  },
  {
    name: "Dr. Farhana Yasmin",
    title: "Consultant Gynecologist & Laparoscopic Surgeon",
    degree: "MBBS, MS (OBGYN), DGO, Fellow in Infertility (India)",
    specialty: "Gynecology & Obstetrics",
    experienceYears: 16,
    city: "Dhaka",
    hospital: "Evercare Hospital Dhaka",
    hospitalAddress: "Plot 81, Block E, Bashundhara R/A, Dhaka",
    fee: 1400,
    rating: 4.8,
    reviewCount: 245,
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Tue", "Thu"],
    timing: "4:00 PM - 8:00 PM",
    bio: "Expert in high-risk pregnancies, laparoscopic ovarian cystectomies, hysterectomies, and IVF fertility consultations.",
    contactPhone: "+880 1711-000222",
    email: "farhana.yasmin@evercarebd.com",
    languages: ["Bangla", "English"],
    gender: "Female",
    isFeatured: true
  },
  {
    name: "Dr. Kamrul Hasan",
    title: "Chief Orthopedic & Joint Replacement Surgeon",
    degree: "MBBS, MS (Orthopedics), Fellowship in Joint Replacement (UK)",
    specialty: "Orthopedics",
    experienceYears: 19,
    city: "Dhaka",
    hospital: "United Hospital Limited",
    hospitalAddress: "Plot 15, Road 71, Gulshan 2, Dhaka",
    fee: 1500,
    rating: 4.9,
    reviewCount: 302,
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Mon", "Wed", "Sat"],
    timing: "4:00 PM - 8:00 PM",
    bio: "Leading orthopedic surgeon performing primary knee & hip replacements, trauma fixations, and keyhole shoulder arthroscopy.",
    contactPhone: "+880 1911-556677",
    email: "dr.kamrul@uhlbd.com",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: true
  },
  {
    name: "Dr. Noshin Tarannum",
    title: "Associate Specialist Pediatrician & Neonatologist",
    degree: "MBBS, DCH (Ireland), MD (Pediatrics)",
    specialty: "Pediatrics",
    experienceYears: 11,
    city: "Dhaka",
    hospital: "Labaid Specialized Hospital",
    hospitalAddress: "House 06, Road 04, Dhanmondi, Dhaka",
    fee: 1000,
    rating: 4.85,
    reviewCount: 215,
    photo: "https://images.unsplash.com/photo-1594824813566-78a1ed6493f8?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Mon", "Tue", "Thu"],
    timing: "5:30 PM - 8:30 PM",
    bio: "Compassionate child healthcare specialist focusing on newborn care, pediatric fever, asthma, growth monitoring, and vaccination.",
    contactPhone: "+880 1712-445566",
    email: "noshin.t@labaidgroup.com",
    languages: ["Bangla", "English"],
    gender: "Female",
    isFeatured: true
  },
  {
    name: "Dr. Nusrat Jahan Ela",
    title: "Consultant Dermatologist & Cosmetic Surgeon",
    degree: "MBBS, DDV (BSMMU), MCPS, Fellow in Aesthetic Medicine (USA)",
    specialty: "Dermatology",
    experienceYears: 10,
    city: "Dhaka",
    hospital: "Ibn Sina Diagnostic & Imaging Center",
    hospitalAddress: "House 48, Road 9/A, Dhanmondi, Dhaka",
    fee: 1100,
    rating: 4.88,
    reviewCount: 278,
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Mon", "Wed", "Sat"],
    timing: "5:00 PM - 9:00 PM",
    bio: "Specializing in clinical dermatology, laser skin resurfacing, hair transplantation, psoriasis treatment, and acne scarring solutions.",
    contactPhone: "+880 1817-223344",
    email: "nusrat.dermatology@ibnsinatrust.com",
    languages: ["Bangla", "English"],
    gender: "Female",
    isFeatured: true
  },
  {
    name: "Prof. Dr. Sabina Sharmin",
    title: "Chief Medical Oncologist",
    degree: "MBBS, FCPS (Radiotherapy), MPhil (Oncology), Fellow UICC",
    specialty: "Oncology",
    experienceYears: 23,
    city: "Dhaka",
    hospital: "Square Hospital",
    hospitalAddress: "Panthapath, Dhaka",
    fee: 1800,
    rating: 4.92,
    reviewCount: 310,
    photo: "https://images.unsplash.com/photo-1594824813566-78a1ed6493f8?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Tue", "Thu"],
    timing: "5:00 PM - 8:00 PM",
    bio: "Leading medical oncologist specializing in breast cancer, colon cancer chemotherapy, immunotherapy, and targeted tumor therapies.",
    contactPhone: "+880 1711-887766",
    email: "sabina.oncology@squarehospital.com",
    languages: ["Bangla", "English"],
    gender: "Female",
    isFeatured: true
  },
  {
    name: "Dr. Kabir Ahmed",
    title: "Consultant Neurosurgeon",
    degree: "MBBS, MS (Neurosurgery), Fellowship in Brain Tumor Surgery (Japan)",
    specialty: "Neurology",
    experienceYears: 18,
    city: "Dhaka",
    hospital: "National Institute of Neurosciences & Hospital",
    hospitalAddress: "Sher-e-Bangla Nagar, Agargaon, Dhaka",
    fee: 1500,
    rating: 4.87,
    reviewCount: 265,
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Mon", "Wed", "Fri"],
    timing: "4:30 PM - 8:30 PM",
    bio: "Pioneer in minimally invasive brain surgery, spinal cord decompression, head injury trauma care, and brain aneurysm clipping.",
    contactPhone: "+880 1715-112233",
    email: "kabir.neurosurgery@nins.gov.bd",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: false
  },
  {
    name: "Dr. Fahmida Zabin",
    title: "Consultant Hematologist & Bone Marrow Transplant Specialist",
    degree: "MBBS, FCPS (Hematology), MD (Clinical Hematology)",
    specialty: "Oncology",
    experienceYears: 14,
    city: "Dhaka",
    hospital: "Evercare Hospital Dhaka",
    hospitalAddress: "Bashundhara R/A, Dhaka",
    fee: 1600,
    rating: 4.83,
    reviewCount: 195,
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Tue", "Thu"],
    timing: "3:00 PM - 7:00 PM",
    bio: "Specialist in leukemia, lymphoma, thalassemia management, anemia diagnostic evaluation, and autologous stem cell transplantation.",
    contactPhone: "+880 1819-445566",
    email: "fahmida.zabin@evercarebd.com",
    languages: ["Bangla", "English"],
    gender: "Female",
    isFeatured: false
  },

  // --- CHITTAGONG DISTRICT (5 Doctors) ---
  {
    name: "Dr. Tanvir Rahman",
    title: "Consultant Neurologist & Stroke Specialist",
    degree: "MBBS, MD (Neurology), Fellowship in Stroke (Singapore)",
    specialty: "Neurology",
    experienceYears: 14,
    city: "Chittagong",
    hospital: "Imperial Hospital Limited",
    hospitalAddress: "Zakir Hossain Road, Pahartali, Chittagong",
    fee: 1200,
    rating: 4.82,
    reviewCount: 210,
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sat", "Mon", "Wed", "Fri"],
    timing: "3:00 PM - 7:00 PM",
    bio: "Specialist in acute stroke thrombolysis, epilepsy care, Parkinson's disease, chronic headache, and peripheral neuropathy.",
    contactPhone: "+880 1812-334455",
    email: "tanvir.neurology@imperialbd.org",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: true
  },
  {
    name: "Dr. Kazi Manwar Hossain",
    title: "Senior Consultant Cardiologist",
    degree: "MBBS, FCPS (Medicine), MD (Cardiology)",
    specialty: "Cardiology",
    experienceYears: 20,
    city: "Chittagong",
    hospital: "Chittagong Medical College & Hospital",
    hospitalAddress: "KB Fazlul Kader Road, Panchlaish, Chittagong",
    fee: 1000,
    rating: 4.79,
    reviewCount: 290,
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Tue", "Thu"],
    timing: "5:00 PM - 9:00 PM",
    bio: "Renowned cardiologist in Chittagong region with 20+ years expertise in hypertension, echocardiography, angiogram, and stent implantation.",
    contactPhone: "+880 1819-112233",
    email: "kazi.manwar@cmch.gov.bd",
    languages: ["Bangla", "English", "Chatgaya"],
    gender: "Male",
    isFeatured: true
  },
  {
    name: "Dr. Sharmin Akter Lipi",
    title: "Consultant Dermatologist & Cosmetologist",
    degree: "MBBS, DDV, FCPS (Dermatology)",
    specialty: "Dermatology",
    experienceYears: 12,
    city: "Chittagong",
    hospital: "Max Hospital & Diagnostic Ltd.",
    hospitalAddress: "35/36 SS Khaled Road, Askar Dighi Par, Chittagong",
    fee: 900,
    rating: 4.76,
    reviewCount: 180,
    photo: "https://images.unsplash.com/photo-1594824813566-78a1ed6493f8?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Mon", "Wed", "Sat"],
    timing: "4:00 PM - 8:00 PM",
    bio: "Popular skin specialist in Chittagong offering advanced laser hair reduction, chemical peels, vitiligo therapy, and eczema care.",
    contactPhone: "+880 1817-556677",
    email: "sharmin.lipi@maxhospitalbd.com",
    languages: ["Bangla", "English"],
    gender: "Female",
    isFeatured: false
  },
  {
    name: "Dr. Ahsanul Kabir",
    title: "Chief Cardiac Surgeon",
    degree: "MBBS, MS (Cardiothoracic Surgery), FRCS (Edinburgh)",
    specialty: "Cardiology",
    experienceYears: 21,
    city: "Chittagong",
    hospital: "Parkview Hospital Limited",
    hospitalAddress: "Catalganj, Panchlaish, Chittagong",
    fee: 1500,
    rating: 4.88,
    reviewCount: 230,
    photo: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Tue", "Wed"],
    timing: "4:30 PM - 8:30 PM",
    bio: "Pioneer heart surgeon in Chittagong performing off-pump coronary artery bypass grafting (CABG) and heart valve repair surgeries.",
    contactPhone: "+880 1819-889900",
    email: "ahsanul.kabir@parkview.com.bd",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: false
  },
  {
    name: "Dr. Meherun Nesa",
    title: "Senior Consultant Gynecologist & Fetal Specialist",
    degree: "MBBS, FCPS (OBGYN), Fellow in Fetal Medicine (Singapore)",
    specialty: "Gynecology & Obstetrics",
    experienceYears: 17,
    city: "Chittagong",
    hospital: "Chevron Clinical Laboratory & Hospital",
    hospitalAddress: "12, OB Nizam Road, Panchlaish, Chittagong",
    fee: 1000,
    rating: 4.81,
    reviewCount: 215,
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sat", "Sun", "Wed"],
    timing: "5:00 PM - 9:00 PM",
    bio: "Specializing in 4D fetal anomaly scans, high-risk twin pregnancies, gynecological ultrasound, and painless normal delivery management.",
    contactPhone: "+880 1818-334455",
    email: "meherun.nesa@chevronbd.com",
    languages: ["Bangla", "English"],
    gender: "Female",
    isFeatured: false
  },

  // --- SYLHET DISTRICT (4 Doctors) ---
  {
    name: "Dr. Shaheen Chowdhury",
    title: "Senior Consultant Gastroenterologist & Hepatologist",
    degree: "MBBS, FCPS (Medicine), MD (Gastroenterology)",
    specialty: "Gastroenterology",
    experienceYears: 17,
    city: "Sylhet",
    hospital: "Popular Diagnostic Centre Sylhet",
    hospitalAddress: "New Medical Road, Kajolshah, Sylhet",
    fee: 900,
    rating: 4.75,
    reviewCount: 162,
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Tue", "Thu", "Fri"],
    timing: "4:30 PM - 8:30 PM",
    bio: "Leading gastroenterologist in Sylhet division performing diagnostic & therapeutic upper GI endoscopy, colonoscopy, and ERCP.",
    contactPhone: "+880 1713-778899",
    email: "shaheen.gastro@populardiagnostic.com",
    languages: ["Bangla", "English", "Sylheti"],
    gender: "Male",
    isFeatured: true
  },
  {
    name: "Dr. Sultana Razia",
    title: "Associate Specialist Pediatrician & Child Cardiologist",
    degree: "MBBS, DCH, FCPS (Pediatrics)",
    specialty: "Pediatrics",
    experienceYears: 13,
    city: "Sylhet",
    hospital: "Mount Adora Hospital Sylhet",
    hospitalAddress: "Nayasark, Sylhet",
    fee: 800,
    rating: 4.79,
    reviewCount: 175,
    photo: "https://images.unsplash.com/photo-1594824813566-78a1ed6493f8?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Mon", "Wed", "Sat"],
    timing: "4:00 PM - 8:00 PM",
    bio: "Dedicated child specialist treating congenital heart defects, neonatal jaundice, pediatric pneumonia, and childhood malnutrition.",
    contactPhone: "+880 1714-223344",
    email: "sultana.razia@mountadora.com",
    languages: ["Bangla", "English", "Sylheti"],
    gender: "Female",
    isFeatured: false
  },
  {
    name: "Dr. Asaduzzaman Choudhury",
    title: "Consultant Pulmonologist & Chest Specialist",
    degree: "MBBS, DTCD, MD (Chest Diseases), FCCP (USA)",
    specialty: "Internal Medicine & Diabetes",
    experienceYears: 16,
    city: "Sylhet",
    hospital: "Al-Haramain Hospital Sylhet",
    hospitalAddress: "Samairgaon, Subidbazar, Sylhet",
    fee: 900,
    rating: 4.82,
    reviewCount: 190,
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Tue", "Thu"],
    timing: "5:00 PM - 9:00 PM",
    bio: "Specializing in bronchial asthma, COPD, tuberculosis (TB), sleep apnea, lung fibrosis, and bronchoscopy diagnostic procedures.",
    contactPhone: "+880 1715-667788",
    email: "asad.chest@alharamain.com.bd",
    languages: ["Bangla", "English", "Sylheti"],
    gender: "Male",
    isFeatured: false
  },
  {
    name: "Prof. Dr. M. A. Osmani",
    title: "Senior Consultant Orthopedic Surgeon",
    degree: "MBBS, MS (Orthopedics), FICS",
    specialty: "Orthopedics",
    experienceYears: 25,
    city: "Sylhet",
    hospital: "Sylhet MAG Osmani Medical College Hospital",
    hospitalAddress: "Kajolshah, Sylhet 3100",
    fee: 1000,
    rating: 4.85,
    reviewCount: 220,
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sat", "Mon", "Wed"],
    timing: "4:00 PM - 8:00 PM",
    bio: "Senior orthopedic consultant treating bone fractures, spinal trauma, joint deformity correction, and pediatric orthopedic disorders.",
    contactPhone: "+880 1711-445566",
    email: "osmani.ortho@somch.gov.bd",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: false
  },

  // --- RAJSHAHI DISTRICT (4 Doctors) ---
  {
    name: "Prof. Dr. Quazi Tarikul Islam",
    title: "Chief Consultant Physician & Medicine Specialist",
    degree: "MBBS, FCPS (Medicine), FACP (USA), FRCP (Edinburgh)",
    specialty: "Internal Medicine & Diabetes",
    experienceYears: 31,
    city: "Rajshahi",
    hospital: "Popular Diagnostic Centre Rajshahi",
    hospitalAddress: "Bandh Gate, Greater Road, Rajshahi",
    fee: 1200,
    rating: 4.93,
    reviewCount: 380,
    photo: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Mon", "Tue", "Wed"],
    timing: "4:00 PM - 9:00 PM",
    bio: "Legendary internal medicine professor in North Bengal. Expert in complex multi-organ disorders, hypertension, and diabetes management.",
    contactPhone: "+880 1711-334455",
    email: "dr.tarikul@rajshahipopular.com",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: true
  },
  {
    name: "Dr. Mahmudul Alam",
    title: "Consultant ENT & Head Neck Surgeon",
    degree: "MBBS, DLO, FCPS (ENT)",
    specialty: "ENT (Ear, Nose, Throat)",
    experienceYears: 15,
    city: "Rajshahi",
    hospital: "Popular Diagnostic Centre Rajshahi",
    hospitalAddress: "Bandh Gate, Greater Road, Rajshahi",
    fee: 800,
    rating: 4.65,
    reviewCount: 140,
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Mon", "Wed", "Fri"],
    timing: "4:00 PM - 8:00 PM",
    bio: "Specialized care for chronic sinusitis, tonsillitis, ear infection microsurgery, and vocal cord polyp surgical removals.",
    contactPhone: "+880 1714-889900",
    email: "mahmudul.ent@rajshahipopular.com",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: false
  },
  {
    name: "Dr. Zobaida Farzana",
    title: "Consultant Gynecologist & Infertility Specialist",
    degree: "MBBS, FCPS (OBGYN), Training in Reproductive Medicine",
    specialty: "Gynecology & Obstetrics",
    experienceYears: 12,
    city: "Rajshahi",
    hospital: "Zamzam Hospital Rajshahi",
    hospitalAddress: "Laxmipur, Rajshahi",
    fee: 800,
    rating: 4.77,
    reviewCount: 165,
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Tue", "Thu"],
    timing: "3:30 PM - 7:30 PM",
    bio: "Dedicated gynecologist treating PCOS, menstrual irregularities, uterine fibroids, and infertility evaluation in Rajshahi region.",
    contactPhone: "+880 1716-112233",
    email: "zobaida.farzana@zamzam.com.bd",
    languages: ["Bangla", "English"],
    gender: "Female",
    isFeatured: false
  },
  {
    name: "Dr. Tariqul Islam Siddiqui",
    title: "Consultant Urologist & Transplant Surgeon",
    degree: "MBBS, MS (Urology)",
    specialty: "Urology",
    experienceYears: 16,
    city: "Rajshahi",
    hospital: "Rajshahi Medical College Hospital",
    hospitalAddress: "Laxmipur, Rajshahi 6000",
    fee: 900,
    rating: 4.81,
    reviewCount: 185,
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sat", "Mon", "Thu"],
    timing: "5:00 PM - 8:30 PM",
    bio: "Specializing in kidney stone laser surgery (URSL / PCNL), prostate enlargement (TURP), laparoscopic urology, and male fertility care.",
    contactPhone: "+880 1712-990011",
    email: "tariqul.urology@rmch.gov.bd",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: false
  },

  // --- KHULNA DISTRICT (4 Doctors) ---
  {
    name: "Prof. Dr. Gazi Abdul Haq",
    title: "Chief Orthopedic & Spine Surgeon",
    degree: "MBBS, MS (Orthopedics), FICS (USA)",
    specialty: "Orthopedics",
    experienceYears: 26,
    city: "Khulna",
    hospital: "Gazi Medical College Hospital",
    hospitalAddress: "A-15/16 Majid Sarani, Sonadanga, Khulna",
    fee: 1000,
    rating: 4.86,
    reviewCount: 270,
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Mon", "Wed"],
    timing: "4:00 PM - 8:30 PM",
    bio: "Senior orthopedic expert in Khulna performing spinal disc surgery, knee replacement, hip fracture fixation, and deformity corrections.",
    contactPhone: "+880 1711-224466",
    email: "gazi.ortho@gazimedical.edu.bd",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: true
  },
  {
    name: "Dr. Taufiqur Rahman Khan",
    title: "Consultant Psychiatrist & Behavioral Therapist",
    degree: "MBBS, MD (Psychiatry), MCPS",
    specialty: "Psychiatry",
    experienceYears: 13,
    city: "Khulna",
    hospital: "Khulna City Medical College & Hospital",
    hospitalAddress: "KDA Avenue, Teligati, Khulna",
    fee: 800,
    rating: 4.78,
    reviewCount: 150,
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sat", "Tue", "Thu"],
    timing: "5:00 PM - 9:00 PM",
    bio: "Empathetic mental health specialist treating clinical depression, anxiety, OCD, bipolar disorder, and child behavioral disorders.",
    contactPhone: "+880 1713-998800",
    email: "taufiq.psychiatry@kcmc.edu.bd",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: false
  },
  {
    name: "Dr. S. M. Mustafizur Rahman",
    title: "Consultant in Physical Medicine & Rehabilitation",
    degree: "MBBS, FCPS (Physical Medicine)",
    specialty: "Orthopedics",
    experienceYears: 15,
    city: "Khulna",
    hospital: "Popular Diagnostic Centre Khulna",
    hospitalAddress: "Shamsur Rahman Road, Khulna",
    fee: 700,
    rating: 4.72,
    reviewCount: 135,
    photo: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Tue", "Wed"],
    timing: "4:30 PM - 8:30 PM",
    bio: "Non-surgical specialist for chronic back pain, cervical spondylosis, stroke rehabilitation, sciatica, and sports injury physical therapy.",
    contactPhone: "+880 1714-556677",
    email: "mustafiz.pmr@khulnapopular.com",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: false
  },
  {
    name: "Dr. Laila Arjumand",
    title: "Senior Consultant Gynecologist",
    degree: "MBBS, DGO, FCPS (OBGYN)",
    specialty: "Gynecology & Obstetrics",
    experienceYears: 19,
    city: "Khulna",
    hospital: "Khulna Surgical & Medical Center",
    hospitalAddress: "Jolil Tower, KDA Avenue, Khulna",
    fee: 900,
    rating: 4.80,
    reviewCount: 195,
    photo: "https://images.unsplash.com/photo-1594824813566-78a1ed6493f8?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Mon", "Wed", "Sat"],
    timing: "4:00 PM - 8:00 PM",
    bio: "Experienced obstetrician in Khulna managing complex obstetric surgical procedures, laparoscopic surgery, and adolescent health.",
    contactPhone: "+880 1712-667788",
    email: "laila.arjumand@khulnasurgical.com",
    languages: ["Bangla", "English"],
    gender: "Female",
    isFeatured: false
  },

  // --- BARISAL DISTRICT (3 Doctors) ---
  {
    name: "Dr. Ruksana Parveen",
    title: "Senior Consultant Gynecologist & Infertility Specialist",
    degree: "MBBS, FCPS (OBGYN), MS",
    specialty: "Gynecology & Obstetrics",
    experienceYears: 18,
    city: "Barisal",
    hospital: "Rahat Anwar Hospital Barisal",
    hospitalAddress: "Band Road, Barisal",
    fee: 800,
    rating: 4.81,
    reviewCount: 185,
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Tue", "Thu"],
    timing: "4:00 PM - 8:00 PM",
    bio: "Leading female health consultant in Barisal division providing expert maternity care, C-section surgery, and fertility treatments.",
    contactPhone: "+880 1711-778899",
    email: "ruksana.gyn@rahatanwar.com",
    languages: ["Bangla", "English"],
    gender: "Female",
    isFeatured: true
  },
  {
    name: "Dr. Shahida Khatun",
    title: "Senior Consultant Pediatrician",
    degree: "MBBS, DCH, MD (Pediatrics)",
    specialty: "Pediatrics",
    experienceYears: 20,
    city: "Barisal",
    hospital: "Sher-e-Bangla Medical College Hospital",
    hospitalAddress: "Band Road, Barisal 8200",
    fee: 700,
    rating: 4.79,
    reviewCount: 160,
    photo: "https://images.unsplash.com/photo-1594824813566-78a1ed6493f8?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sat", "Mon", "Wed"],
    timing: "5:00 PM - 8:30 PM",
    bio: "Senior pediatrician in Barisal with two decades of experience treating pediatric infectious diseases, malnutrition, and childhood fever.",
    contactPhone: "+880 1712-889900",
    email: "shahida.pedia@sbmch.gov.bd",
    languages: ["Bangla", "English"],
    gender: "Female",
    isFeatured: false
  },
  {
    name: "Dr. Nazmul Huda",
    title: "Consultant Cardiologist",
    degree: "MBBS, MD (Cardiology)",
    specialty: "Cardiology",
    experienceYears: 14,
    city: "Barisal",
    hospital: "Popular Diagnostic Centre Barisal",
    hospitalAddress: "Kawnia Main Road, Barisal",
    fee: 800,
    rating: 4.74,
    reviewCount: 142,
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Tue", "Fri"],
    timing: "4:00 PM - 8:00 PM",
    bio: "Heart care specialist evaluating ischemic heart disease, chest pain diagnosis, ECG interpretation, and blood pressure regulation.",
    contactPhone: "+880 1713-112233",
    email: "nazmul.cardio@barisalpopular.com",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: false
  },

  // --- RANGPUR DISTRICT (3 Doctors) ---
  {
    name: "Dr. Mizanur Rahman",
    title: "Chief Endocrinologist & Diabetologist",
    degree: "MBBS, MD (Endocrinology, BIRDEM)",
    specialty: "Internal Medicine & Diabetes",
    experienceYears: 16,
    city: "Rangpur",
    hospital: "Prime Medical College Hospital",
    hospitalAddress: "Pirjabad, Badarganj Road, Rangpur",
    fee: 800,
    rating: 4.83,
    reviewCount: 205,
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sat", "Mon", "Wed"],
    timing: "4:30 PM - 8:30 PM",
    bio: "Diabetes & hormone specialist in Rangpur managing Type 1 & Type 2 diabetes, thyroid disorders, obesity, and adrenal issues.",
    contactPhone: "+880 1715-443322",
    email: "mizanur.endo@primemedical.edu.bd",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: true
  },
  {
    name: "Dr. Mosharraf Hossain",
    title: "Consultant General & Laparoscopic Surgeon",
    degree: "MBBS, FCPS (Surgery)",
    specialty: "Orthopedics",
    experienceYears: 18,
    city: "Rangpur",
    hospital: "Doctor's Clinic Rangpur",
    hospitalAddress: "Jail Road, Dhap, Rangpur",
    fee: 700,
    rating: 4.76,
    reviewCount: 155,
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Tue", "Thu"],
    timing: "5:00 PM - 9:00 PM",
    bio: "Laparoscopic surgeon performing keyhole gallbladder removal (cholecystectomy), hernia repair, appendectomy, and thyroidectomy.",
    contactPhone: "+880 1716-554433",
    email: "mosharraf.surgery@doctorsclinicbd.com",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: false
  },
  {
    name: "Dr. Rokeya Begum",
    title: "Consultant Gynecologist & Obstetrician",
    degree: "MBBS, DGO, MCPS",
    specialty: "Gynecology & Obstetrics",
    experienceYears: 15,
    city: "Rangpur",
    hospital: "Rangpur Medical College Hospital",
    hospitalAddress: "Dhap, Rangpur 5400",
    fee: 700,
    rating: 4.75,
    reviewCount: 148,
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Mon", "Wed", "Fri"],
    timing: "4:00 PM - 8:00 PM",
    bio: "Senior obstetrician offering antenatal consultation, high-risk delivery care, postpartum recovery advice, and cervical cancer screening.",
    contactPhone: "+880 1717-889900",
    email: "rokeya.gyn@rpch.gov.bd",
    languages: ["Bangla", "English"],
    gender: "Female",
    isFeatured: false
  },

  // --- MYMENSINGH DISTRICT (3 Doctors) ---
  {
    name: "Dr. Shamim Ahmed",
    title: "Chief Nephrologist & Kidney Transplant Specialist",
    degree: "MBBS, MD (Nephrology), Fellow ISN",
    specialty: "Internal Medicine & Diabetes",
    experienceYears: 17,
    city: "Mymensingh",
    hospital: "Nexus Hospital Mymensingh",
    hospitalAddress: "128, Mymensingh Sadar, Mymensingh",
    fee: 900,
    rating: 4.84,
    reviewCount: 198,
    photo: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sat", "Mon", "Thu"],
    timing: "4:00 PM - 8:30 PM",
    bio: "Leading kidney specialist in Mymensingh region managing chronic kidney disease (CKD), hemodialysis supervision, and glomerulonephritis.",
    contactPhone: "+880 1718-223344",
    email: "shamim.kidney@nexushospitalbd.com",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: true
  },
  {
    name: "Dr. Nahid Sultana",
    title: "Consultant Ophthalmologist & Phaco Eye Surgeon",
    degree: "MBBS, DO (BSMMU), FCPS (Ophthalmology)",
    specialty: "ENT (Ear, Nose, Throat)",
    experienceYears: 12,
    city: "Mymensingh",
    hospital: "Mymensingh Eye Hospital",
    hospitalAddress: "Charpara, Mymensingh",
    fee: 600,
    rating: 4.78,
    reviewCount: 130,
    photo: "https://images.unsplash.com/photo-1594824813566-78a1ed6493f8?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Tue", "Wed"],
    timing: "3:30 PM - 7:30 PM",
    bio: "Eye microsurgeon performing stitchless Phaco cataract surgery, glaucoma screening, diabetic retinopathy laser care, and pediatric vision checkup.",
    contactPhone: "+880 1719-556677",
    email: "nahid.eye@mymensingheye.com",
    languages: ["Bangla", "English"],
    gender: "Female",
    isFeatured: false
  },
  {
    name: "Dr. Anupam Das",
    title: "Senior Consultant Medicine Specialist",
    degree: "MBBS, FCPS (Medicine)",
    specialty: "Internal Medicine & Diabetes",
    experienceYears: 21,
    city: "Mymensingh",
    hospital: "Mymensingh Medical College Hospital",
    hospitalAddress: "Charpara, Mymensingh 2200",
    fee: 800,
    rating: 4.80,
    reviewCount: 170,
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Mon", "Wed", "Sat"],
    timing: "5:00 PM - 9:00 PM",
    bio: "Renowned general physician managing Dengue, Typhoid, unexplained fever, adult immunization, and liver disease.",
    contactPhone: "+880 1711-667788",
    email: "anupam.das@mmch.gov.bd",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: false
  },

  // --- COMILLA DISTRICT (3 Doctors) ---
  {
    name: "Dr. Anisur Rahman",
    title: "Consultant Neurologist & Stroke Specialist",
    degree: "MBBS, MD (Neurology)",
    specialty: "Neurology",
    experienceYears: 15,
    city: "Comilla",
    hospital: "Moon Hospital Comilla",
    hospitalAddress: "Jhautala, Comilla",
    fee: 900,
    rating: 4.80,
    reviewCount: 168,
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Tue", "Thu"],
    timing: "4:00 PM - 8:00 PM",
    bio: "Expert neurologist in Comilla managing stroke rehabilitation, paralysis, bell's palsy, nerve weakness, and migraine headache.",
    contactPhone: "+880 1712-334455",
    email: "anisur.neuro@moonhospital.com",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: true
  },
  {
    name: "Dr. Tariqul Alam Bhuiyan",
    title: "Consultant Gastroenterologist",
    degree: "MBBS, MD (Gastroenterology)",
    specialty: "Gastroenterology",
    experienceYears: 14,
    city: "Comilla",
    hospital: "Central Hospital Comilla",
    hospitalAddress: "Reazuddin Bazar, Comilla",
    fee: 800,
    rating: 4.73,
    reviewCount: 145,
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sat", "Mon", "Wed"],
    timing: "5:00 PM - 9:00 PM",
    bio: "Gastroenterology specialist treating peptic ulcer disease, GERD, fatty liver, jaundice, colitis, and diagnostic stomach endoscopy.",
    contactPhone: "+880 1713-445566",
    email: "tariqul.gastro@comillacentral.com",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: false
  },
  {
    name: "Dr. Nazma Sultana",
    title: "Consultant Gynecologist",
    degree: "MBBS, FCPS (OBGYN)",
    specialty: "Gynecology & Obstetrics",
    experienceYears: 16,
    city: "Comilla",
    hospital: "Comilla Medical College Hospital",
    hospitalAddress: "Kuchaitali, Comilla",
    fee: 800,
    rating: 4.79,
    reviewCount: 162,
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Tue", "Fri"],
    timing: "3:30 PM - 7:30 PM",
    bio: "Senior obstetrician in Comilla delivering complete maternal care, laparoscopic ovarian cyst surgery, and menopause consultations.",
    contactPhone: "+880 1714-998877",
    email: "nazma.gyn@comec.gov.bd",
    languages: ["Bangla", "English"],
    gender: "Female",
    isFeatured: false
  },

  // --- BOGURA DISTRICT (2 Doctors) ---
  {
    name: "Dr. Monjurul Islam",
    title: "Consultant Urologist & Endourologist",
    degree: "MBBS, MS (Urology)",
    specialty: "Urology",
    experienceYears: 13,
    city: "Bogura",
    hospital: "TMSS Medical College & Hospital",
    hospitalAddress: "Rangpur Road, Thengamara, Bogura",
    fee: 800,
    rating: 4.79,
    reviewCount: 152,
    photo: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sat", "Mon", "Wed"],
    timing: "4:00 PM - 8:00 PM",
    bio: "Skilled endourologist performing laser surgery for kidney stones, prostate enlargement therapy, and urinary infection treatments in Bogura.",
    contactPhone: "+880 1715-998877",
    email: "monjurul.urology@tmssmedical.edu.bd",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: true
  },
  {
    name: "Dr. Golam Sarwar",
    title: "Chief Orthopedic & Trauma Surgeon",
    degree: "MBBS, MS (Orthopedics)",
    specialty: "Orthopedics",
    experienceYears: 17,
    city: "Bogura",
    hospital: "Shaheed Ziaur Rahman Medical College Hospital",
    hospitalAddress: "Silimpur, Bogura 5800",
    fee: 800,
    rating: 4.82,
    reviewCount: 180,
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=500&auto=format&fit=crop&q=80",
    availableDays: ["Sun", "Tue", "Thu"],
    timing: "5:00 PM - 9:00 PM",
    bio: "Senior orthopedic trauma surgeon in Bogura treating complex bone fractures, road accident injuries, joint dislocations, and arthritis pain.",
    contactPhone: "+880 1716-113355",
    email: "golam.sarwar@szrmc.gov.bd",
    languages: ["Bangla", "English"],
    gender: "Male",
    isFeatured: false
  }
];

const hospitalsData = [
  {
    name: "Square Hospital Ltd.",
    type: "Tertiary Care Private Hospital",
    city: "Dhaka",
    address: "18/F, Bir Uttam Qazi Nuruzzaman Sarak, Panthapath, Dhaka 1205",
    phone: "+880 2-8159457",
    emergencyHotline: "10616",
    totalBeds: 400,
    availableICUBeds: 12,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&auto=format&fit=crop&q=80",
    departments: ["Cardiology", "Oncology", "Neurology", "Orthopedics", "Gynecology", "Pediatrics", "ICU & Emergency"],
    facilities: ["24/7 Emergency", "Coronary Care Unit", "Helipad Service", "Advanced Diagnostic Lab", "Pharmacy", "Ambulance"],
    establishedYear: 2006
  },
  {
    name: "Evercare Hospital Dhaka",
    type: "JCI Accredited Multi-Specialty Hospital",
    city: "Dhaka",
    address: "Plot 81, Block E, Bashundhara R/A, Dhaka 1229",
    phone: "+880 2-8431661",
    emergencyHotline: "10678",
    totalBeds: 425,
    availableICUBeds: 15,
    rating: 4.85,
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&auto=format&fit=crop&q=80",
    departments: ["Cardiology", "Neurosurgery", "Gastroenterology", "Nephrology", "Transplant Unit", "Pediatric ICU"],
    facilities: ["JCI Accredited", "24/7 Trauma Care", "Robotic Surgery", "Blood Bank", "International Patient Care"],
    establishedYear: 2005
  },
  {
    name: "Labaid Specialized Hospital",
    type: "Cardiac & Specialized Medical Center",
    city: "Dhaka",
    address: "House 06, Road 04, Dhanmondi, Dhaka 1205",
    phone: "+880 2-9676356",
    emergencyHotline: "10606",
    totalBeds: 250,
    availableICUBeds: 8,
    rating: 4.75,
    image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800&auto=format&fit=crop&q=80",
    departments: ["Cardiology", "Cardiothoracic Surgery", "Kidney Care", "General Surgery", "Radiology"],
    facilities: ["Cath Lab", "Open Heart Surgery", "Executive Health Checkup", "Dialysis Center", "24/7 Pharmacy"],
    establishedYear: 2004
  },
  {
    name: "United Hospital Limited",
    type: "Super-Specialty Hospital",
    city: "Dhaka",
    address: "Plot 15, Road 71, Gulshan 2, Dhaka 1212",
    phone: "+880 2-9852413",
    emergencyHotline: "10666",
    totalBeds: 500,
    availableICUBeds: 18,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=800&auto=format&fit=crop&q=80",
    departments: ["Heart Centre", "Neuro Centre", "Oncology Centre", "Orthopedic Centre", "Critical Care"],
    facilities: ["Linear Accelerator", "PET-CT Scan", "Stroke Unit", "Neonatal ICU", "Air Ambulance Service"],
    establishedYear: 2006
  },
  {
    name: "BSMMU (Bangabandhu Sheikh Mujib Medical University)",
    type: "Premier Autonomous Public Medical University & Hospital",
    city: "Dhaka",
    address: "Shahbag, Dhaka 1000",
    phone: "+880 2-55165760",
    emergencyHotline: "02-55165600",
    totalBeds: 1500,
    availableICUBeds: 25,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=800&auto=format&fit=crop&q=80",
    departments: ["Internal Medicine", "Rheumatology", "Endocrinology", "Pediatrics", "Urology", "Physical Medicine"],
    facilities: ["Super-Specialized Hospital Unit", "Research Labs", "Low-cost Quality Care", "National Reference Lab"],
    establishedYear: 1998
  },
  {
    name: "Imperial Hospital Limited",
    type: "State-of-the-Art Tertiary Care Center",
    city: "Chittagong",
    address: "Zakir Hossain Road, Pahartali, Chittagong",
    phone: "+880 31-659000",
    emergencyHotline: "09612-222333",
    totalBeds: 375,
    availableICUBeds: 10,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&auto=format&fit=crop&q=80",
    departments: ["Cardiology", "Neurology", "Mother & Child Care", "Diagnostic Imaging", "Emergency & Trauma"],
    facilities: ["Modern Operation Theatres", "Child-Friendly Ward", "Dialysis Unit", "24/7 Ambulance"],
    establishedYear: 2019
  }
];

const costsData = [
  {
    procedureName: "Coronary Angiogram (CAG)",
    category: "Cardiology",
    avgCostBDT: 25000,
    minCostBDT: 18000,
    maxCostBDT: 35000,
    duration: "Day Care / 1 Day Stay",
    hospitalType: "Private Tertiary Hospital",
    description: "Diagnostic procedure to evaluate coronary artery blockage using contrast material and X-ray imaging.",
    includes: ["Cath Lab Charges", "Cardiologist Fee", "Contrast Media", "1 Day Bed Charge"]
  },
  {
    procedureName: "Coronary Angioplasty (Stenting - 1 Stent)",
    category: "Cardiology",
    avgCostBDT: 180000,
    minCostBDT: 140000,
    maxCostBDT: 260000,
    duration: "2 - 3 Days Stay",
    hospitalType: "Private Specialized Center",
    description: "Percutaneous coronary intervention with FDA-approved Drug-Eluting Stent (DES) insertion.",
    includes: ["1 US-FDA Drug Eluting Stent", "Cath Lab & ICU stay", "Surgeon & Anesthesia Fees", "Medicines"]
  },
  {
    procedureName: "Normal Vaginal Delivery (NVD)",
    category: "Maternity & Gynecology",
    avgCostBDT: 35000,
    minCostBDT: 20000,
    maxCostBDT: 55000,
    duration: "1 - 2 Days Stay",
    hospitalType: "Private / General Hospital",
    description: "Spontaneous normal childbirth with continuous fetal monitoring and pediatrician newborn assessment.",
    includes: ["Delivery Room Charges", "Obstetrician & Pediatrician Fee", "Standard Cabin Stay", "Newborn Routine Care"]
  },
  {
    procedureName: "Cesarean Section (C-Section Surgery)",
    category: "Maternity & Gynecology",
    avgCostBDT: 65000,
    minCostBDT: 45000,
    maxCostBDT: 110000,
    duration: "3 - 4 Days Stay",
    hospitalType: "Private Tertiary Hospital",
    description: "Surgical delivery procedure performed under spinal or epidural anesthesia.",
    includes: ["OT Charges", "Surgeon, Anesthetist & Pediatrician Fees", "3 Days Cabin Stay", "Post-op Care"]
  },
  {
    procedureName: "Whole Body MRI Scan (1.5T / 3.0T)",
    category: "Diagnostic & Imaging",
    avgCostBDT: 12000,
    minCostBDT: 8500,
    maxCostBDT: 18000,
    duration: "Outpatient (45 Mins)",
    hospitalType: "Diagnostic Center / Hospital",
    description: "High-resolution Magnetic Resonance Imaging scan for precise anatomical cross-section evaluation.",
    includes: ["Scan Procedure", "Contrast (if applicable)", "Radiologist Official Report"]
  },
  {
    procedureName: "Total Knee Replacement (Single Knee)",
    category: "Orthopedics & Surgery",
    avgCostBDT: 280000,
    minCostBDT: 220000,
    maxCostBDT: 380000,
    duration: "5 - 7 Days Stay",
    hospitalType: "Specialized Orthopedic Hospital",
    description: "Surgical replacement of damaged knee joint components with imported high-grade prosthetic implant.",
    includes: ["Imported Knee Prosthesis", "OT & Anesthesia", "Post-op Physiotherapy", "Cabin & ICU Stay"]
  },
  {
    procedureName: "ICU Bed Charge (Per Day)",
    category: "ICU & Critical Care",
    avgCostBDT: 15000,
    minCostBDT: 8000,
    maxCostBDT: 28000,
    duration: "Daily Rate",
    hospitalType: "Private Tertiary Hospital",
    description: "24/7 intensive monitoring bed with dedicated nursing ratio (1:1) and mechanical ventilator setup.",
    includes: ["Bed & Monitor Charges", "1:1 Dedicated Nursing", "Resident Medical Officer Duty", "Oxygen Supply"]
  },
  {
    procedureName: "Cataract Surgery (Phaco Surgery + IOL)",
    category: "Ophthalmology / Eye",
    avgCostBDT: 30000,
    minCostBDT: 18000,
    maxCostBDT: 55000,
    duration: "Outpatient (2 Hours)",
    hospitalType: "Specialized Eye Hospital",
    description: "Sutureless micro-incision Phacoemulsification eye surgery with foldable Intraocular Lens (IOL).",
    includes: ["Foldable Intraocular Lens", "Phaco Machine & OT Fee", "Surgeon Fee", "Post-op Eye Drops"]
  }
];

const specialistsData = [
  { name: "Cardiology", description: "Heart, coronary artery diseases, blood pressure & pacemakers", icon: "HeartPulse", count: 120 },
  { name: "Gynecology & Obstetrics", description: "Women's reproductive health, maternity care, and fertility treatment", icon: "UserCheck", count: 150 },
  { name: "Neurology", description: "Brain, spinal cord, stroke, epilepsy, and nervous system disorders", icon: "Brain", count: 85 },
  { name: "Orthopedics", description: "Bone fractures, joint replacements, arthritis, and spine care", icon: "Bone", count: 95 },
  { name: "Pediatrics", description: "Child health, infant nutrition, vaccination, and growth monitoring", icon: "Baby", count: 110 },
  { name: "Gastroenterology", description: "Stomach, liver, digestion, acid reflux, and endoscopy care", icon: "Activity", count: 70 },
  { name: "Oncology", description: "Cancer diagnosis, chemotherapy, radiation, and surgical oncology", icon: "ShieldAlert", count: 60 },
  { name: "Dermatology", description: "Skin, hair loss, laser skin care, and allergic reactions", icon: "Sparkles", count: 90 },
  { name: "ENT (Ear, Nose, Throat)", description: "Sinusitis, hearing disorders, throat surgery, and tonsils", icon: "Stethoscope", count: 65 },
  { name: "Rheumatology", description: "Rheumatoid arthritis, lupus, joint inflammation, and gout", icon: "Thermometer", count: 45 }
];

async function seed() {
  try {
    const { db } = await connectToDatabase();

    console.log("Clearing existing collections...");
    await db.collection("doctors").deleteMany({});
    await db.collection("hospitals").deleteMany({});
    await db.collection("costs").deleteMany({});
    await db.collection("specialists").deleteMany({});

    console.log("Inserting Doctors data...");
    const doctorRes = await db.collection("doctors").insertMany(doctorsData);
    console.log(`Successfully inserted ${doctorRes.insertedCount} doctors into 'doctors' collection.`);

    console.log("Inserting Hospitals data...");
    const hospitalRes = await db.collection("hospitals").insertMany(hospitalsData);
    console.log(`Successfully inserted ${hospitalRes.insertedCount} hospitals into 'hospitals' collection.`);

    console.log("Inserting Treatment Costs data...");
    const costRes = await db.collection("costs").insertMany(costsData);
    console.log(`Successfully inserted ${costRes.insertedCount} treatment cost records into 'costs' collection.`);

    console.log("Inserting Specialist Categories data...");
    const specRes = await db.collection("specialists").insertMany(specialistsData);
    console.log(`Successfully inserted ${specRes.insertedCount} specialist categories into 'specialists' collection.`);

    console.log("--- SEEDING COMPLETED SUCCESSFULLY ---");
    process.exit(0);
  } catch (err) {
    console.error("Seeding error:", err);
    process.exit(1);
  }
}

seed();
